# Generated by Django 5.1.6 on 2025-03-09 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4, verbose_name='Type')),
                ('date', models.DateTimeField(verbose_name='Date created')),
                ('datasets', models.JSONField(verbose_name='Datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(verbose_name='Values')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.method')),
            ],
        ),
    ]
