# Generated by Django 5.1.6 on 2025-03-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_experiment_classifier_experiment_scaler'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(verbose_name='Values')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.experiment')),
            ],
        ),
    ]
